services:
  - type: web
    name: cow-bot
    env: node
    region: singapore
    plan: free
    buildCommand: npm install --no-audit --no-fund
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: "20.18.0"
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
    autoDeploy: true
