services:
    - type: web
      name: nar-bot
      env: node
      region: oregon
      plan: free
      nodeVersion: 20.18.0
      buildCommand: npm install --production=false
      startCommand: node index.js
      healthCheckPath: /ping
      autoDeploy: true
      envVars:
        - key: NODE_ENV
          value: production
  