services:
  - type: web
    name: nar-bot
    env: node
    region: oregon
    plan: free
    buildCommand: npm install --production=false
    startCommand: node index.js
    healthCheckPath: /ping
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20.18.0"
